apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: danielworkspace

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml

commonLabels:
  app: finedimondo
  project: fine-di-mondo

commonAnnotations:
  managed-by: "kustomize"
  version: "1.0.0"

replicas:
  - name: finedimondo-backend
    count: 2
  - name: finedimondo-frontend
    count: 2
